### ISSUE TITLE
Add a `CODEOWNERS` file to this repo

### ISSUE THREAD

**Issue by cemms1** [guardian/manage-frontend#1320]
There is no `CODEOWNERS` file in this repo so pull requests are not automatically assigned to the team marked as owners.

[Repocop](https://metrics.gutools.co.uk/d/EOPnljWIz/repocop-compliance) says the owners are @guardian/retention 

Please could you add a `CODEOWNERS` file indicating which team is responsible for this code to help future contributors get relevant reviews and approvals?

**Comment by tjmw** [comment]
Fixed by #1334 - thanks for pointing this out @cemms1, sorry it took a while to action!
